### ISSUE TITLE
Kubernetes document

### ISSUE THREAD

**Issue by diguage** [diguage/puddle#2]
1. [Configure a Pod to Use a PersistentVolume for Storage - Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) -- `task-pv-volume` 与 `task-pv-claim` 之间没有声明有依赖关系，为啥会自动建立关联？

**Comment by diguage** [comment]
1

> After you create the PersistentVolumeClaim, the Kubernetes control plane looks for a PersistentVolume that satisfies the claim’s requirements. If the control plane finds a suitable PersistentVolume with the same StorageClass, it binds the claim to the volume.

**Comment by diguage** [comment]
[Configure a Security Context for a Pod or Container - Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) 
这里面关于 Linux 的文档都读一读。

**Comment by diguage** [comment]
The securityContext field is a SecurityContext object.

**Comment by diguage** [comment]
学习一下 Linux capabilities：

1. [capabilities(7) - Linux manual page](http://man7.org/linux/man-pages/man7/capabilities.7.html)
1. [linux/capability.h at master · torvalds/linux](https://github.com/torvalds/linux/blob/master/include/uapi/linux/capability.h) -- definitions of the capability constants.

**Comment by diguage** [comment]
`cd /proc/1` 别有洞天， `cat /proc/1/status` 大开眼界。学习一下 Linux 进程表示。

**Comment by diguage** [comment]
如何搭建私有的 Docker Image Registry ？如果在 Kubernetes 集群中配置统一的私有 Registry？

**Comment by diguage** [comment]
如果清理掉 Kubernetes 集群中，不再使用的 Docker Image？

**Comment by diguage** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
    name: init-demo
spec:
    containers:
        - name: nginx-ctr
          image: nginx
          ports:
              - containerPort: 80
          volumeMounts:
              - name: workdir
                mountPath: /usr/share/nginx/html  // 这个地方先是写成了 /user， 更正之后，使用 kubectl apply -f init-containers.yaml 更新 Pod 报错
    initContainers:
        - name: install
          image: busybox
          command:
              - wget
              - "-O"
              - "/work-dir/index.html"
              - https://kubernetes.io
          volumeMounts:
              - name: workdir
                mountPath: "/work-dir"
    dnsPolicy: Default
    volumes:
        - name: workdir
          emptyDir: {}
```

错误日志：

```
➜ kubectl apply -f init-containers.yaml
The Pod "init-demo" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
  	Volumes:        []core.Volume{{Name: "workdir", VolumeSource: core.VolumeSource{EmptyDir: &core.EmptyDirVolumeSource{}}}, {Name: "default-token-pm7m9", VolumeSource: core.VolumeSource{Secret: &core.SecretVolumeSource{SecretName: "default-token-pm7m9", DefaultMode: &420}}}},
  	InitContainers: []core.Container{{Name: "install", Image: "busybox", Command: []string{"wget", "-O", "/work-dir/index.html", "https://kubernetes.io"}, VolumeMounts: []core.VolumeMount{{Name: "workdir", MountPath: "/work-dir"}, {Name: "default-token-pm7m9", ReadOnly: true, MountPath: "/var/run/secrets/kubernetes.io/serviceaccount"}}, TerminationMessagePath: "/dev/termination-log", TerminationMessagePolicy: "File", ImagePullPolicy: "Always"}},
  	Containers: []core.Container{
  		{
  			... // 7 identical fields
  			Env:       nil,
  			Resources: core.ResourceRequirements{},
  			VolumeMounts: []core.VolumeMount{
  				{
- 					Name:             "default-token-pm7m9",
+ 					Name:             "workdir",
- 					ReadOnly:         true,
+ 					ReadOnly:         false,
- 					MountPath:        "/var/run/secrets/kubernetes.io/serviceaccount",
+ 					MountPath:        "/user/share/nginx/html",
  					SubPath:          "",
  					MountPropagation: nil,
  					SubPathExpr:      "",
  				},
  				{
- 					Name:             "workdir",
+ 					Name:             "default-token-pm7m9",
- 					ReadOnly:         false,
+ 					ReadOnly:         true,
- 					MountPath:        "/usr/share/nginx/html",
+ 					MountPath:        "/var/run/secrets/kubernetes.io/serviceaccount",
  					SubPath:          "",
  					MountPropagation: nil,
  					SubPathExpr:      "",
  				},
  			},
  			VolumeDevices: nil,
  			LivenessProbe: nil,
  			... // 9 identical fields
  		},
  	},
  	RestartPolicy:                 "Always",
  	TerminationGracePeriodSeconds: &30,
  	... // 21 identical fields
  }
```

**Comment by diguage** [comment]
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
```

这里的 `requests` 和 `limits` 怎么跟其他地方写法如此不协调？
